#!/hpc/local/CentOS7/dhl_ec/software/R-3.6.3/R-3.6.3/bin/Rscript --vanilla

# Script for calculating the cumulative sum of risk scores generated by PLINK.
# This is required when you have multiple risk scores (e.g. one for each chromosome) and you would like to know the sum of these scores.

# Required packages
packages = c("optparse",
            "data.table")

## Load and install packages if necessary
package.check <- lapply(
  packages,
  FUN = function(x) {
    if (!require(x, character.only = TRUE)) {
      install.packages(x, dependencies = TRUE, repos='http://cran.us.r-project.org')
      try(library(x), silent=TRUE)
    }
  }
)

# Parse arguments from commandline
args <- commandArgs(trailingOnly = TRUE)
option_list = list(
  make_option(c("-s", "--sample"), action="store", default=NA, type='character', help="Path to the sample file"),
  make_option(c("-f", "--sfidcol"), action="store", default=NA, type='character', help="FID column position in the sample file (start from 1)"),
  make_option(c("-i", "--siidcol"), action="store", default=NA, type='character', help="IID column position in the sample file (start from 1)"),
  make_option(c("-d", "--scoredir"), action="store", default=NA, type='character', help="Directory in which the risk scores reside"),
  make_option(c("-p", "--scoreprefix"), action="store", default=NA, type='character', help="Prefix of the risk score files"),
  make_option(c("-r", "--rscorecol"), action="store", default=NA, type='character', help="Name of the risk score column in the score files"),
  make_option(c("-o", "--out"), action="store", default=NA, type='character', help="Path to the output file")
)

opt = parse_args(OptionParser(option_list=option_list))

print(opt)

# Read the sample file to a table
sumscores <- read.table(opt$sample, sep='', header=TRUE)

# List all the files containing scores that contribute to the final risk score    
files <- list.files(path=opt$scoredir, pattern=paste("^", opt$scoreprefix, ".+\\.sscore$", sep=""), full.names=TRUE, recursive=FALSE)

# For each file, add the score column to the sumscores table
for (file in files) {
  chr_scores <- fread(file, sep='\t', header=TRUE)
  column_list <- c(1, 2, which(names(chr_scores) == opt$rscorecol))
  chr_scores <- subset(chr_scores, select=column_list)
  names(chr_scores) <- c("FID", "IID", file)
  sumscores <- merge(x=sumscores, y=chr_scores, all.x, by.x=c(1, 2), by.y=c(1, 2))
}

# Compute the sum of all the added columns 
sumscores$SCORE <- rowSums(sumscores[ , c(files)], na.rm=TRUE)

# Write the sample file with the added risk score to the output file
export <- sumscores[, c(1, 2, which(names(sumscores) == "SCORE"))]
write.table(export, file=opt$out, row.names=FALSE, sep="\t", quote=FALSE)
